### ISSUE TITLE
Automating SHA256 env var set

### ISSUE THREAD

**Issue by anthcor** [djenriquez/nomad#1]
Would be super awesome if we could automate the sha setting from the nomad version a user specifies by pulling info from the pages HashiCorp exposes :: https://releases.hashicorp.com/nomad/0.5.1/nomad_0.5.1_SHA256SUMS.

**Comment by djenriquez** [comment]
Hmmm, that would be nice. I'll set up some kind of script that can extract that when I find some time. Otherwise if someone else can beat me to it, that'd be great also 😁 👍
